# Generated by Django 3.2 on 2022-01-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'about us', 'verbose_name_plural': 'about us'},
        ),
        migrations.AlterModelOptions(
            name='chef',
            options={'verbose_name': 'chef', 'verbose_name_plural': 'chef'},
        ),
        migrations.AlterModelOptions(
            name='why_choose_us',
            options={'verbose_name': 'why choose us', 'verbose_name_plural': 'why choose us'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='why_choose_us',
            name='content',
            field=models.TextField(),
        ),
    ]
