# Generated by Django 3.2 on 2022-01-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0002_auto_20220130_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='heading',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='chef',
            name='paragrapgH',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='why_choose_us',
            name='heading',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AddField(
            model_name='why_choose_us',
            name='paragrapgH',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
    ]
