# Generated by Django 3.2 on 2022-01-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0004_auto_20220130_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='chef',
            name='paragrapgH',
        ),
        migrations.RemoveField(
            model_name='why_choose_us',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='why_choose_us',
            name='paragrapgH',
        ),
    ]
