# Generated by Django 3.2 on 2022-01-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0005_auto_20220130_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(default='image', upload_to='about_us/'),
        ),
    ]
