# Generated by Django 3.2 on 2022-01-25 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20220125_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meals',
            name='preparation_time',
        ),
    ]