# Generated by Django 3.2 on 2022-01-26 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_meals_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'verbose_name': 'meal', 'verbose_name_plural': 'meals'},
        ),
    ]
