# Generated by Django 3.2 on 2022-02-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
