# Generated by Django 3.2 on 2022-02-26 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0030_auto_20220226_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user',
            new_name='manger',
        ),
    ]
