# Generated by Django 3.2 on 2022-02-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0031_rename_user_reservation_manger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='manger',
            new_name='user',
        ),
    ]
