# Generated by Django 3.2 on 2022-02-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0032_rename_manger_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.IntegerField(default=1),
        ),
    ]
